src/carts/urls.py
from django.urls import path


from .views import (
	cart_home, 
	cart_update,
	checkout_home,
	checkout_dene_view,
	)

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/success',checkout_dene_view, name='success'),
    path('checkout/',checkout_home, name='checkout'),
    path('update/',cart_update, name='update'),
    
]

app_name = 'carts'

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from django.views.generic import TemplateView

from accounts.views import login_page, register_page, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from .views import home_page, about_page, contact_page 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home'),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('login/', login_page, name='login'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register_view'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cart/', include("carts.urls", namespace='cart')),
    path('register/', register_page, name='register'),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('products/', include("products.urls", namespace='products')),
    path('search/', include("search.urls", namespace='search')),


]


if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path


from .views import (
	ProductListView, 
	ProductDetailSlugView,
	)

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('/<slug:slug>/', ProductDetailSlugView.as_view(), name='detail'),
    

]

app_name = 'products'

src/templates/base/css.html
{% load static %}

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">


<!-- Fontawesome CSS -->

<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

src/templates/base/js.html
{% load static %}

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'about' as about_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ home_url }}">{% if brand_name %} {{ brand_name }} {% else %}eco{% endif %}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_url %} active {% endif%}" aria-current="page" href="{{ home_url }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == contact_url %} active {% endif%}" aria-current="page" href="{{ contact_url }}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == about_url %} active {% endif%}" aria-current="page" href="{{ about_url }}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == products_list_url %} active {% endif%}" aria-current="page" href="{{ products_list_url }}">Products</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == logout_url %} active {% endif%}" aria-current="page" href="{{ logout_url }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == register_url %} active {% endif%}" aria-current="page" href="{{ register_url }}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == login_url %} active {% endif%}" aria-current="page" href="{{ login_url }}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == cart_url %} active {% endif%}" aria-current="page" href="{{ cart_url }}">{{ request.session.cart_items }}<i class="fa fa-shopping-cart" aria-hidden="true"></i> </a>
        </li>
      </ul>
      {% include 'search/snippets/search-form.html' %}
    </div>
  </div>
</nav>